name: Build EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build EXE
        run: pyinstaller --onefile automasi_merge_invoice.py

      - name: Upload EXE
        uses: actions/upload-artifact@v3
        with:
          name: exe-output
          path: dist/
